VOCAB_BOOK_BASE_URL = "https://api.frdic.com/api/open/v1/studylist/category"
GET_WORD_URL = "https://api.frdic.com/api/open/v1/studylist/words"
DEFAULT_VOCAB_BOOK_NAME = "我的生词本"
VOCAB_BOOK_NAME = "name"
VOCAB_BOOK_ID = "id"
